// frontend/src/routes/solo.tsx
// Authentication and routing imports
import { useAuth0 } from '@auth0/auth0-react'
import { createFileRoute } from '@tanstack/react-router'

// React core imports
import { useState, useEffect, useRef } from 'react'

// Custom hooks for timer and competition management
import { useCubeTimer } from '../hooks/useCubeTimer'
import { useSoloCompetition } from '../hooks/useSoloCompetition'

// Component imports
import { Scramble } from '../components/Scramble'
import { Timer } from '../components/Timer'
import { SoloResult } from '../components/SoloResult'
import { CubePreview3d } from '../components/CubePreview3d'

// Type imports
import type { CompetitionState } from '../api/solo'

// Create the route definition for the solo solving page
export const Route = createFileRoute('/solo')({
  component: SoloComponent,
})

function SoloComponent() {
  // Auth0 authentication hooks
  const { isLoading, isAuthenticated, loginWithRedirect, getAccessTokenSilently } = useAuth0();

  // Timer state management from custom hook
  const { 
    time,           // Current time value (reactive)
    startTimer,     // Function to start the timer
    stopTimer,      // Function to stop the timer
    resetTimer,     // Function to reset the timer
  } = useCubeTimer();

  // Local state management
  const [session, setSession] = useState<CompetitionState | null>(null);        // Current solving session state
  const [currentState, setCurrentState] = useState<SessionState>('scrambling'); // Current solve state (scrambling/solving)
  const [isModalOpen, setIsModalOpen] = useState(false);                        // Controls result modal visibility

  // Competition management hook with session update callback
  const { 
    connectionState,    // Current WebSocket connection state
    error,             // Any error messages
    initialize: apiInitializeConnection,  // Function to initialize WebSocket connection
    startSolve: apiStartSolve,           // API call to start a solve
    completeSolve: apiCompleteSolve,     // API call to complete a solve
    startSession: apiStartSession,        // API call to start a new session
    updatePenalty: apiUpdatePenalty      // API call to update solve penalty
  } = useSoloCompetition((session) => setSession(session));

  // Initialize WebSocket connection when component mounts or auth state changes
  useEffect(() => {
    apiInitializeConnection();
  }, [isAuthenticated, apiInitializeConnection]);

  // Update local state when session state changes
  useEffect(() => {
    if (session) {
      setCurrentState(session.state);
    }
  }, [session]);
  // Event handlers for keydown/keyup
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.code !== 'Space') return;
      if (connectionState !== 'connected') return;

      if (currentState === 'scrambling') {
        handleStartSolve();
      } else if (currentState === 'solving') {
        handleCompleteSolve();
      }

    };

    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [currentState, connectionState]);

  // Handler for starting a new solve
  const handleStartSolve = () => {
    if (connectionState !== 'connected') return;

    resetTimer();
    startTimer();
    apiStartSolve();
  };

  // Handler for completing a solve
  const handleCompleteSolve = () => {
    if (connectionState !== 'connected') return;
    console.log('Solve completed:', time);

    const finalTime = time;
    stopTimer();
    apiCompleteSolve(finalTime);
    setIsModalOpen(true);
  };

  // Handler for starting a new session
  const handleNewSession = () => {
    if (connectionState !== 'connected') return;

    resetTimer();
    apiStartSession();
    setIsModalOpen(false);
  };

  // Handler for updating solve penalties
  const handlePenaltyChange = (penalty: Penalty) => {
    if (connectionState !== 'connected') return;
    apiUpdatePenalty(penalty);
  };

  // Loading state render
  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center h-screen">
        <div className="text-xl text-skin-base animate-pulse">Loading...</div>
      </div>
    );
  }

  // Unauthenticated state render
  if (!isAuthenticated) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <button
          onClick={() => loginWithRedirect()}
          className="px-4 py-2 bg-skin-accent text-skin-base text-lg rounded hover:opacity-90 transition-opacity"
        >
          Login
        </button>
      </div>
    );
  }

  // Error state render when no session is available
  if (!session) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <p className="text-skin-accent text-lg">
          {error || 'Error: No session found'}
        </p>
      </div>
    );
  }

  // Main component render
  return (
    <div className="flex flex-row">
      <div className="grow flex flex-col items-center">
        {/* Connection status banner */}
        {connectionState !== 'connected' && (
          <div
            className={`w-full p-2 text-center text-skin-base ${
              connectionState === 'connecting' 
                ? 'bg-skin-accent bg-opacity-50' 
                : 'bg-skin-accent'
            }`}
          >
            {connectionState === 'connecting' ? 'Connecting...' : 'Disconnected'}
          </div>
        )}
        
        {/* Error message display */}
        {error && (
          <div className="w-full p-2 bg-skin-accent text-skin-base text-center">
            {error}
          </div>
        )}

        {/* Scramble display */}
        <Scramble scramble={session.scramble} />
        
        {/* 3D cube preview (only shown during scrambling) */}
        {currentState === 'scrambling' && (
          <CubePreview3d scramble={session.scramble} />
        )}

        {/* Timer component */}
        <Timer
          time={time}
        />

        {/* Results modal */}
        <SoloResult
          isOpen={isModalOpen}
          onClose={handleNewSession}
          session={session}
          time={time}
          onPenaltyChange={handlePenaltyChange}
        />
      </div>
    </div>
  );
}

// client/pages/solo.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useAuth } from '~/composables/useAuth';
import { useAuthenticatedWebsocket } from '~/composables/useAuthenticatedWebsocket';
import { Result } from '#components'

const config = useRuntimeConfig();
const { loading, authenticated, login } = useAuth();
const { timer, startTimer, stopTimer, resetTimer } = useCubeTimer();
const { formatTime } = useTimeFormat();
const { createWebSocket } = useAuthenticatedWebsocket();
const modal = useModal();
const session = ref<CompetitionState | null>(null);
let ws: WebSocket;

onMounted(async () => {
  ws = await createWebSocket(`ws://${config.public.apiUrl}/competition/ws`);

  ws.onopen = () => {
    startSession();
  };

  ws.onmessage = (event) => {
    const message = JSON.parse(event.data);
    if (message.type === 'SESSION_UPDATE') {
      updateSession(message.payload);
    }
  };
});

function updateSession(payload: CompetitionState) {
  console.log(payload);
  session.value = payload;
  if (payload.state === 'complete') {
    // In case it is a penalty update, close the modal first
    modal.close();
    modal.open(Result, {
      session: payload,
      ui: { width: 'w-fit' },
      preventClose: true,
      "onUpdatePenalty": (param: Penalty) => {
        console.log(param);
        updatePenalty(param);
      },
      "onClose": () => {
        startSession();
      }
    });
  }
}

function startSession() {
  resetTimer();
  const message: WebSocketMessage = {
    type: 'SOLO_START',
    payload: { cube_type: "3x3" }
  }
  ws.send(JSON.stringify(message));
}

function startSolve() {
  startTimer();
  const message: WebSocketMessage = {
    type: 'READY',
  }
  ws.send(JSON.stringify(message));
}

function completeSolve() {
  stopTimer();
  const message: WebSocketMessage = {
    type: 'SOLVE_COMPLETE',
    payload: { time: timer.value }
  }
  ws.send(JSON.stringify(message));
}

function updatePenalty(penalty: Penalty) {

  const message: WebSocketMessage = {
    type: 'PENALTY',
    payload: { penalty }
  }
  ws.send(JSON.stringify(message));
}
</script>

<template>
  <div v-if="loading" class="flex-1 flex items-center justify-center h-screen">
    <div class="text-xl text-gray-600 dark:text-white animate-pulse">Loading...</div>
  </div>
  <div v-else-if="!authenticated" class="flex-1 flex items-center justify-center">
    <button @click="login" class="px-4 py-2 bg-indigo-800 text-white text-lg rounded hover:bg-blue-700">
      Login
    </button>
  </div>
  <!-- Main Timer Interface -->
  <div v-if="session" class="flex flex-row">
    <!-- Left Column: Timer and Controls -->
    <div class="grow flex flex-col items-center">
      <!-- Scramble Display -->
      <div class="w-full p-2 rounded shadow-sm bg-gray-800">
        <p class="text-center text-gray-800 dark:text-white font-mono text-4xl">{{ session.scramble }}</p>
      </div>

      <!-- Timer Display -->
      <div class="font-mono text-[20em] flex flex-row items-center h-2/3">
        {{ formatTime(timer) }}
      </div>

      <!-- Control Buttons -->
      <div class="space-x-2">
        <button v-if="session.state === 'scrambling'" @click="startSolve"
          class="px-4 py-2 bg-green-600 text-white text-lg rounded hover:bg-green-700">
          Start
        </button>
        <button v-else-if="session.state === 'solving'" @click="completeSolve"
          class="px-4 py-2 bg-red-600 text-white text-lg rounded hover:bg-red-700">
          Stop
        </button>
      </div>
    </div>

    <!-- Right Column: Preview and Solves List 
    <div class="flex-inital flex flex-col items-center ml-4">
      <div class="w-full h-40 bg-gray-200 mb-4 rounded flex items-center justify-center">
        <p class="text-gray-500 font-mono text-lg px-5">Cube Preview</p>
      </div>

      <div class="w-full bg-gray-100 p-4 rounded shadow-sm">
        <h2 class="text-lg font-semibold text-gray-700 mb-2">Solves</h2>
        <ul>
          <li v-for="solve in [12.34, 10.56, 9.87]" :key="solve" class="font-mono text-gray-800 text-sm mb-1">
            {{ solve }} s
          </li>
        </ul>
      </div>
    </div -->
  </div>

  <div v-else class="flex-1 flex items-center justify-center">
    <p class="text-red-500 text-lg">Error: No session found</p>
  </div>
</template>

<style scoped>
/* Prevent text selection during timing */
.font-mono {
  user-select: none;
}

/* Prevent double-tap zoom on mobile */
button {
  touch-action: manipulation;
}
</style>
