// frontend/src/routes/solo.tsx
import { useAuth0 } from '@auth0/auth0-react'
import { useCubeTimer } from '../hooks/useCubeTimer'
import { Scramble } from '../components/Scramble'
import { Timer } from '../components/Timer'
import type { CompetitionState } from '../api/solo'
import { useSoloCompetition } from '../hooks/useSoloCompetition'
import { createFileRoute } from '@tanstack/react-router'
import { useState, useEffect, useRef } from 'react'
import { SoloResult } from '../components/SoloResult'
import { CubePreview3d } from '../components/CubePreview3d'

export const Route = createFileRoute('/solo')({
  component: SoloComponent,
})

function SoloComponent() {
  const { isLoading, isAuthenticated, loginWithRedirect } = useAuth0();
  const { 
    time, 
    startTimer, 
    stopTimer, 
    resetTimer, 
  } = useCubeTimer();
  const [session, setSession] = useState<CompetitionState | null>(null);
  const [currentState, setCurrentState] = useState<SessionState>('scrambling');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const { getAccessTokenSilently } = useAuth0();
  
  const { 
    connectionState, 
    error, 
    initialize, 
    startSolve: apiStartSolve, 
    completeSolve: apiCompleteSolve,
    startSession: apiStartSession,
    updatePenalty: apiUpdatePenalty
  } = useSoloCompetition((session) => setSession(session));

  useEffect(() => {
    initialize(`wss://api.speedsolve.xyz/competition/ws`);
  }, [isAuthenticated, initialize]);

  useEffect(() => {
    if (session) {
      setCurrentState(session.state);
    }
  }, [session]);

  const handleStartSolve = () => {
    if (connectionState !== 'connected') return;

    resetTimer();
    startTimer();
    apiStartSolve();
  };

  const handleCompleteSolve = () => {
    if (connectionState !== 'connected') return;

    const finalTime = time;
    stopTimer();
    apiCompleteSolve(finalTime);
    setIsModalOpen(true);
  };

  const handleNewSession = () => {
    if (connectionState !== 'connected') return;

    resetTimer();
    apiStartSession();
    setIsModalOpen(false);
  };

  const handlePenaltyChange = (penalty: Penalty) => {
    if (connectionState !== 'connected') return;
    apiUpdatePenalty(penalty);
  };

  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center h-screen">
        <div className="text-xl text-skin-base animate-pulse">Loading...</div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <button
          onClick={() => loginWithRedirect()}
          className="px-4 py-2 bg-skin-accent text-skin-base text-lg rounded hover:opacity-90 transition-opacity"
        >
          Login
        </button>
      </div>
    );
  }

  if (!session) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <p className="text-skin-accent text-lg">
          {error || 'Error: No session found'}
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-row">
      <div className="grow flex flex-col items-center">
        {connectionState !== 'connected' && (
          <div
            className={`w-full p-2 text-center text-skin-base ${
              connectionState === 'connecting' 
                ? 'bg-skin-accent bg-opacity-50' 
                : 'bg-skin-accent'
            }`}
          >
            {connectionState === 'connecting' ? 'Connecting...' : 'Disconnected'}
          </div>
        )}
        
        {error && (
          <div className="w-full p-2 bg-skin-accent text-skin-base text-center">
            {error}
          </div>
        )}

        <Scramble scramble={session.scramble} />
        
        {currentState === 'scrambling' && (
          <CubePreview3d scramble={session.scramble} />
        )}

        <Timer
          time={time}
          onStart={handleStartSolve}
          onStop={handleCompleteSolve}
          canStart={connectionState === 'connected' && currentState === 'scrambling'}
          currentState={currentState}
        />

        <SoloResult
          isOpen={isModalOpen}
          onClose={handleNewSession}
          session={session}
          time={time}
          onPenaltyChange={handlePenaltyChange}
        />
      </div>
    </div>
  );
}

// legacy/client/pages/solo.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useAuth } from '~/composables/useAuth'
import { useCompetitionStore } from '~/composables/useCompetitionStore'
import { useCompetition } from '~/composables/useCompetition'

const { loading, authenticated, login } = useAuth()
const { timer, startTimer, stopTimer, resetTimer } = useCubeTimer()
const { formatTime } = useTimeFormat()
const store = useCompetitionStore()
const { initializeSession, startSolve, completeSolve } = useCompetition()

onMounted(async () => {
  if (authenticated) {
    await initializeSession()
  }
})

// Timer handlers
function handleStartSolve() {
  resetTimer()
  startTimer()
  startSolve()
}

function handleCompleteSolve() {
  stopTimer()
  completeSolve(timer.value)
}
</script>

<template>
  <div v-if="loading" class="flex-1 flex items-center justify-center h-screen">
    <div class="text-xl text-gray-600 dark:text-white animate-pulse">Loading...</div>
  </div>

  <div v-else-if="!authenticated" class="flex-1 flex items-center justify-center">
    <button @click="login" class="px-4 py-2 bg-indigo-800 text-white text-lg rounded hover:bg-blue-700">
      Login
    </button>
  </div>

  <!-- Main Timer Interface -->
  <div v-else-if="store.session" class="flex flex-row">
    <!-- Left Column: Timer and Controls -->
    <div class="grow flex flex-col items-center">
      <!-- Connection Status -->
      <div v-if="store.connectionState !== 'connected'" class="w-full p-2 text-center" :class="{
        'bg-yellow-600': store.connectionState === 'connecting',
        'bg-red-600': store.connectionState === 'disconnected'
      }">
        {{ store.connectionState === 'connecting' ? 'Connecting...' : 'Disconnected' }}
      </div>

      <!-- Error Display -->
      <div v-if="store.error" class="w-full p-2 bg-red-600 text-white text-center">
        {{ store.error }}
      </div>

      <!-- Scramble Display -->
      <div class="w-full p-2 rounded shadow-sm bg-gray-800">
        <p class="text-center text-gray-800 dark:text-white font-mono text-4xl">
          {{ store.currentScramble }}
        </p>
      </div>

      <!-- Timer Display -->
      <div class="font-mono text-[20em] flex flex-row items-center h-2/3">
        {{ formatTime(timer) }}
      </div>

      <!-- Control Buttons -->
      <div class="space-x-2">
        <button v-if="store.currentState === 'scrambling'" @click="handleStartSolve"
          class="px-4 py-2 bg-green-600 text-white text-lg rounded hover:bg-green-700" :disabled="!store.canStart">
          Start
        </button>
        <button v-else-if="store.currentState === 'solving'" @click="handleCompleteSolve"
          class="px-4 py-2 bg-red-600 text-white text-lg rounded hover:bg-red-700">
          Stop
        </button>
      </div>
    </div>

    <!-- Right Column: Stats (commented out for now) -->
    <!-- <div class="flex-initial flex flex-col items-center ml-4">...</div> -->
  </div>

  <div v-else class="flex-1 flex items-center justify-center">
    <p class="text-red-500 text-lg">
      {{ store.error || 'Error: No session found' }}
    </p>
  </div>
</template>

<style scoped>
/* Prevent text selection during timing */
.font-mono {
  user-select: none;
}

/* Prevent double-tap zoom on mobile */
button {
  touch-action: manipulation;
}
</style>
